# Generated by Django 2.0 on 2019-04-25 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_added',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='guid',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='title',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='title',
            name='meta_data',
            field=models.TextField(blank=True),
        ),
    ]
