# Generated by Django 2.2.1 on 2019-09-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0004_auto_20190517_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='notify_by',
        ),
        migrations.AddField(
            model_name='profile',
            name='email_notifications',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='inapp_notifications',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='sms_notifications',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
